/**
 * Shared utilities for Vite codegen plugins.
 *
 * Both `surfacesCodegen` and `sidepanelsCodegen` are now thin wrappers
 * around `createCodegenPlugin` here, eliminating ~400 LOC of near-
 * identical boilerplate. Issue #42.
 */

import fs from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";

/** Normalize a path to always use forward slashes (for import paths and Vite compatibility on Windows). */
export function toPosixPath(p: string): string {
  return p.split(path.sep).join("/");
}

/** Convert kebab-case to PascalCase: "create-staff" → "CreateStaff" */
export function toPascalCase(kebab: string): string {
  return kebab
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/** Convert kebab-case to Title Case: "create-staff" → "Create Staff" */
export function toTitleCase(kebab: string): string {
  return kebab
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

/**
 * Configuration for `createCodegenPlugin`. Captures everything that
 * differs between the surfaces and sidepanels codegen plugins; the
 * shared algorithm — discover files, scaffold empties, generate barrel —
 * is identical for both.
 *
 * Issue #42.
 */
export interface CodegenPluginSpec {
  /** Plugin name shown in Vite logs. */
  pluginName: string;
  /** Default directory relative to project root. */
  defaultDirectory: string;
  /** Filename suffix pattern (e.g. /\.panel\.tsx$/). */
  filePattern: RegExp;
  /** Regex matching `export const X = define...(` — captures the const name. */
  defineRegex: RegExp;
  /** Output filename for the generated barrel (relative to `_registry/`). */
  genFilename: string;
  /** The `export const <BarrelExport> = { ... }` name in the barrel. */
  barrelExportName: string;
  /** ANSI-tagged log prefix for run/scaffold messages. */
  logTag: string;
  /**
   * Builds scaffold content for an empty file.
   * `name` is the kebab-cased filename stem (e.g. `manage-role`).
   * `relPath` is the file's path relative to the codegen directory.
   */
  buildScaffold: (name: string, relPath: string) => string;
}

/**
 * Strips the file extension. We compute `relPath.replace(".tsx", "")` to
 * match the prior implementation, but if a future spec uses `.ts` files
 * we'd want a more robust strip. For now this exactly preserves the
 * pre-refactor output.
 */
function stripExtension(relPath: string): string {
  return relPath.replace(/\.tsx?$/, "");
}

/** Recursively gather files matching the pattern under `dir`. */
function getMatchingFiles(dir: string, pattern: RegExp): string[] {
  if (!fs.existsSync(dir)) return [];
  const results: string[] = [];

  function walk(d: string): void {
    for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
      if (entry.name === "_registry") continue;
      const fullPath = path.join(d, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (pattern.test(entry.name)) {
        results.push(toPosixPath(path.relative(dir, fullPath)));
      }
    }
  }

  walk(dir);
  return results.sort();
}

/**
 * Build the generated-barrel file content. Emits a const object with
 * one entry per discovered export, sorted alphabetically by const name.
 */
function buildBarrelContent(
  spec: CodegenPluginSpec,
  entries: Array<{ constName: string; relPath: string }>,
): string {
  if (entries.length === 0) {
    return `// AUTO-GENERATED by ${spec.pluginName} — DO NOT EDIT
// No entries found. Create a file matching ${spec.filePattern} to get started.

export const ${spec.barrelExportName} = {} as const
`;
  }

  const sorted = [...entries].sort((a, b) =>
    a.constName.localeCompare(b.constName),
  );
  const imports = sorted
    .map(
      (e) =>
        `import { ${e.constName} } from '../${stripExtension(e.relPath)}'`,
    )
    .join("\n");
  const members = sorted.map((e) => `  ${e.constName},`).join("\n");

  return `// AUTO-GENERATED by ${spec.pluginName} — DO NOT EDIT

${imports}

export const ${spec.barrelExportName} = {
${members}
} as const
`;
}

/**
 * Scaffolds empty files (writing the spec's `buildScaffold` content)
 * and generates the barrel.
 */
function runCodegen(dir: string, spec: CodegenPluginSpec): void {
  // Pass 1: scaffold any empty file.
  for (const relPath of getMatchingFiles(dir, spec.filePattern)) {
    const filepath = path.join(dir, relPath);
    const content = fs.readFileSync(filepath, "utf-8");
    if (content.trim().length === 0) {
      const name = path.basename(relPath).replace(spec.filePattern, "");
      fs.writeFileSync(filepath, spec.buildScaffold(name, relPath), "utf-8");
      console.log(`${spec.logTag} Scaffolded ${relPath}`);
    }
  }

  // Pass 2: collect define-call exports.
  const entries: Array<{ constName: string; relPath: string }> = [];
  for (const relPath of getMatchingFiles(dir, spec.filePattern)) {
    const filepath = path.join(dir, relPath);
    const content = fs.readFileSync(filepath, "utf-8");
    const match = content.match(spec.defineRegex);
    if (match) entries.push({ constName: match[1], relPath });
  }

  // Pass 3: write the barrel only if content changed (avoid HMR loops).
  const genPath = path.join(dir, "_registry", spec.genFilename);
  const newContent = buildBarrelContent(spec, entries);
  const existing = fs.existsSync(genPath)
    ? fs.readFileSync(genPath, "utf-8")
    : "";
  if (existing !== newContent) {
    fs.writeFileSync(genPath, newContent, "utf-8");
    console.log(
      `${spec.logTag} Regenerated ${spec.genFilename} (${entries.length} entr${entries.length === 1 ? "y" : "ies"})`,
    );
  }
}

/**
 * Factory for codegen Vite plugins. Both surfaces-codegen and
 * sidepanels-codegen are thin wrappers around this. Issue #42.
 */
export function createCodegenPlugin(
  spec: CodegenPluginSpec,
  options?: { directory?: string },
): Plugin {
  const dir = options?.directory ?? spec.defaultDirectory;
  let resolvedDir: string;

  return {
    name: spec.pluginName,
    configResolved(config) {
      resolvedDir = toPosixPath(path.resolve(config.root, dir));
    },
    buildStart() {
      runCodegen(resolvedDir, spec);
    },
    hotUpdate({ file }) {
      if (
        file.startsWith(resolvedDir) &&
        !file.includes("_registry") &&
        spec.filePattern.test(path.basename(file))
      ) {
        runCodegen(resolvedDir, spec);
      }
    },
  };
}

/** Re-exported for actions/plugins.ts which scans these files independently. */
export function listMatchingFiles(
  dir: string,
  pattern: RegExp,
): string[] {
  return getMatchingFiles(dir, pattern);
}
