/**
 * Vite plugin: sidepanels-codegen
 *
 * Watches for *.panel.tsx files, auto-scaffolds empty ones, and generates
 * a typed barrel file (_registry/panel-definitions.gen.ts) on every change.
 *
 * Usage in vite.config.ts:
 *   import { sidepanelsCodegen } from 'chowbea-axios/vite'
 *   export default defineConfig({ plugins: [sidepanelsCodegen()] })
 */

import fs from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";
import { toPascalCase, toPosixPath, toTitleCase } from "./shared.js";

export interface SidepanelsCodegenOptions {
  /** Directory containing side panel components (relative to project root). */
  directory?: string;
}

const PANEL_FILE_PATTERN = /\.panel\.tsx$/;
export const DEFINE_PANEL_REGEX =
  /export\s+const\s+(\w+)\s*=\s*definePanel\s*\(/;
const GEN_FILENAME = "panel-definitions.gen.ts";
const TAG = "\x1b[36m[sidepanels-codegen]\x1b[0m";

/** Extract panel name from filename: "manage-role.panel.tsx" → "manage-role" */
function getPanelName(filename: string): string {
  return filename.replace(PANEL_FILE_PATTERN, "");
}

/** Build scaffold content for an empty *.panel.tsx file */
export function buildPanelScaffold(panelName: string, relPath: string): string {
  const pascal = toPascalCase(panelName);
  const title = toTitleCase(panelName);
  const depth = relPath.split("/").length - 1;
  const prefix = depth > 0 ? "../".repeat(depth) : "./";

  return `import { z } from 'zod'
import { definePanel, usePanelParams, SidePanelBody, SidePanelNavBar } from '${prefix}_registry'

function ${pascal}Panel() {
  const { myParam } = usePanelParams(${pascal})
  return (
    <>
      <SidePanelNavBar>
        <span className="font-medium text-sm">${title}</span>
      </SidePanelNavBar>
      <SidePanelBody>
        <div>{/* content */}</div>
      </SidePanelBody>
    </>
  )
}

export const ${pascal} = definePanel('${panelName}', {
  component: ${pascal}Panel,
  contextParams: z.object({ myParam: z.string() }),
})
`;
}

/** Build the generated barrel file content */
function buildGenFile(
  entries: Array<{ constName: string; relPath: string }>,
): string {
  if (entries.length === 0) {
    return `// AUTO-GENERATED by sidepanels-codegen — DO NOT EDIT
// No panels found. Create a *.panel.tsx file to get started.

export const Panel = {} as const
`;
  }

  const sorted = [...entries].sort((a, b) =>
    a.constName.localeCompare(b.constName),
  );

  const imports = sorted
    .map(
      (e) =>
        `import { ${e.constName} } from '../${e.relPath.replace(".tsx", "")}'`,
    )
    .join("\n");

  const members = sorted.map((e) => `  ${e.constName},`).join("\n");

  return `// AUTO-GENERATED by sidepanels-codegen — DO NOT EDIT

${imports}

export const Panel = {
${members}
} as const
`;
}

/** Recursively get all *.panel.tsx files in the side-panels directory */
export function getPanelFiles(sidePanelsDir: string): Array<string> {
  if (!fs.existsSync(sidePanelsDir)) return [];
  const results: Array<string> = [];

  function walk(dir: string) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.name === "_registry") continue;
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (PANEL_FILE_PATTERN.test(entry.name)) {
        results.push(toPosixPath(path.relative(sidePanelsDir, fullPath)));
      }
    }
  }

  walk(sidePanelsDir);
  return results.sort();
}

/** Scaffold empty files and return whether any were scaffolded */
function scaffoldEmptyFiles(sidePanelsDir: string): boolean {
  let scaffolded = false;

  for (const relPath of getPanelFiles(sidePanelsDir)) {
    const filepath = path.join(sidePanelsDir, relPath);
    const content = fs.readFileSync(filepath, "utf-8");

    if (content.trim().length === 0) {
      const panelName = getPanelName(path.basename(relPath));
      fs.writeFileSync(
        filepath,
        buildPanelScaffold(panelName, relPath),
        "utf-8",
      );
      console.log(`${TAG} Scaffolded ${relPath}`);
      scaffolded = true;
    }
  }

  return scaffolded;
}

/** Scan panel files and generate the barrel */
function generateBarrel(sidePanelsDir: string): void {
  const entries: Array<{ constName: string; relPath: string }> = [];

  for (const relPath of getPanelFiles(sidePanelsDir)) {
    const filepath = path.join(sidePanelsDir, relPath);
    const content = fs.readFileSync(filepath, "utf-8");
    const match = content.match(DEFINE_PANEL_REGEX);

    if (match) {
      entries.push({ constName: match[1], relPath });
    }
  }

  const genPath = path.join(sidePanelsDir, "_registry", GEN_FILENAME);
  const newContent = buildGenFile(entries);

  // Only write if changed to avoid infinite HMR loops
  const existing = fs.existsSync(genPath)
    ? fs.readFileSync(genPath, "utf-8")
    : "";

  if (existing !== newContent) {
    fs.writeFileSync(genPath, newContent, "utf-8");
    console.log(
      `${TAG} Regenerated ${GEN_FILENAME} (${entries.length} panel${entries.length === 1 ? "" : "s"})`,
    );
  }
}

/** Run both scaffolding and barrel generation */
function run(sidePanelsDir: string): void {
  scaffoldEmptyFiles(sidePanelsDir);
  generateBarrel(sidePanelsDir);
}

export function sidepanelsCodegen(
  options?: SidepanelsCodegenOptions,
): Plugin {
  const dir = options?.directory ?? "src/components/side-panels";
  let sidePanelsDir: string;

  return {
    name: "sidepanels-codegen",
    configResolved(config) {
      sidePanelsDir = toPosixPath(path.resolve(config.root, dir));
    },
    buildStart() {
      run(sidePanelsDir);
    },
    hotUpdate({ file }) {
      if (
        file.startsWith(sidePanelsDir) &&
        !file.includes("_registry") &&
        PANEL_FILE_PATTERN.test(path.basename(file))
      ) {
        run(sidePanelsDir);
      }
    },
  };
}
