/**
 * Vite plugin: surfaces-codegen
 *
 * Watches for *.surface.tsx files, auto-scaffolds empty ones, and generates
 * a typed barrel file (_registry/surface-definitions.gen.ts) on every change.
 *
 * Usage in vite.config.ts:
 *   import { surfacesCodegen } from 'chowbea-axios/vite'
 *   export default defineConfig({ plugins: [surfacesCodegen()] })
 */

import fs from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";
import { toPascalCase, toPosixPath, toTitleCase } from "./shared.js";

export interface SurfacesCodegenOptions {
  /** Directory containing surface components (relative to project root). */
  directory?: string;
}

const SURFACE_FILE_PATTERN = /\.surface\.tsx$/;
export const DEFINE_SURFACE_REGEX =
  /export\s+const\s+(\w+)\s*=\s*defineSurface\s*\(/;
const GEN_FILENAME = "surface-definitions.gen.ts";
const TAG = "\x1b[36m[surfaces-codegen]\x1b[0m";

/** Extract surface name from filename: "create-staff.surface.tsx" → "create-staff" */
function getSurfaceName(filename: string): string {
  return filename.replace(SURFACE_FILE_PATTERN, "");
}

/** Build scaffold content for an empty *.surface.tsx file */
export function buildSurfaceScaffold(surfaceName: string, relPath: string): string {
  const pascal = toPascalCase(surfaceName);
  const title = toTitleCase(surfaceName);
  const depth = relPath.split("/").length - 1;
  const prefix = depth > 0 ? "../".repeat(depth) : "./";

  return `import {
  defineSurface,
  SurfaceContainer,
  SurfaceContent,
  SurfaceHeader,
  SurfaceTitle,
} from '${prefix}_registry'

export const ${pascal} = defineSurface('${surfaceName}', {})

export function ${pascal}Surface() {
  return (
    <SurfaceContainer surface={${pascal}}>
      <SurfaceContent>
        <SurfaceHeader>
          <SurfaceTitle>${title}</SurfaceTitle>
        </SurfaceHeader>
        {/* content */}
      </SurfaceContent>
    </SurfaceContainer>
  )
}
`;
}

/** Build the generated barrel file content */
function buildGenFile(
  entries: Array<{ constName: string; relPath: string }>,
): string {
  if (entries.length === 0) {
    return `// AUTO-GENERATED by surfaces-codegen — DO NOT EDIT
// No surfaces found. Create a *.surface.tsx file to get started.

export const Surface = {} as const
`;
  }

  const sorted = [...entries].sort((a, b) =>
    a.constName.localeCompare(b.constName),
  );

  const imports = sorted
    .map(
      (e) =>
        `import { ${e.constName} } from '../${e.relPath.replace(".tsx", "")}'`,
    )
    .join("\n");

  const members = sorted.map((e) => `  ${e.constName},`).join("\n");

  return `// AUTO-GENERATED by surfaces-codegen — DO NOT EDIT

${imports}

export const Surface = {
${members}
} as const
`;
}

/** Recursively get all *.surface.tsx files in the surfaces directory */
export function getSurfaceFiles(surfacesDir: string): Array<string> {
  if (!fs.existsSync(surfacesDir)) return [];
  const results: Array<string> = [];

  function walk(dir: string) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.name === "_registry") continue;
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (SURFACE_FILE_PATTERN.test(entry.name)) {
        results.push(toPosixPath(path.relative(surfacesDir, fullPath)));
      }
    }
  }

  walk(surfacesDir);
  return results.sort();
}

/** Scaffold empty files and return whether any were scaffolded */
function scaffoldEmptyFiles(surfacesDir: string): boolean {
  let scaffolded = false;

  for (const relPath of getSurfaceFiles(surfacesDir)) {
    const filepath = path.join(surfacesDir, relPath);
    const content = fs.readFileSync(filepath, "utf-8");

    if (content.trim().length === 0) {
      const surfaceName = getSurfaceName(path.basename(relPath));
      fs.writeFileSync(
        filepath,
        buildSurfaceScaffold(surfaceName, relPath),
        "utf-8",
      );
      console.log(`${TAG} Scaffolded ${relPath}`);
      scaffolded = true;
    }
  }

  return scaffolded;
}

/** Scan surface files and generate the barrel */
function generateBarrel(surfacesDir: string): void {
  const entries: Array<{ constName: string; relPath: string }> = [];

  for (const relPath of getSurfaceFiles(surfacesDir)) {
    const filepath = path.join(surfacesDir, relPath);
    const content = fs.readFileSync(filepath, "utf-8");
    const match = content.match(DEFINE_SURFACE_REGEX);

    if (match) {
      entries.push({ constName: match[1], relPath });
    }
  }

  const genPath = path.join(surfacesDir, "_registry", GEN_FILENAME);
  const newContent = buildGenFile(entries);

  // Only write if changed to avoid infinite HMR loops
  const existing = fs.existsSync(genPath)
    ? fs.readFileSync(genPath, "utf-8")
    : "";

  if (existing !== newContent) {
    fs.writeFileSync(genPath, newContent, "utf-8");
    console.log(
      `${TAG} Regenerated ${GEN_FILENAME} (${entries.length} surface${entries.length === 1 ? "" : "s"})`,
    );
  }
}

/** Run both scaffolding and barrel generation */
function run(surfacesDir: string): void {
  scaffoldEmptyFiles(surfacesDir);
  generateBarrel(surfacesDir);
}

export function surfacesCodegen(options?: SurfacesCodegenOptions): Plugin {
  const dir = options?.directory ?? "src/components/surfaces";
  let surfacesDir: string;

  return {
    name: "surfaces-codegen",
    configResolved(config) {
      surfacesDir = toPosixPath(path.resolve(config.root, dir));
    },
    buildStart() {
      run(surfacesDir);
    },
    hotUpdate({ file }) {
      if (
        file.startsWith(surfacesDir) &&
        !file.includes("_registry") &&
        SURFACE_FILE_PATTERN.test(path.basename(file))
      ) {
        run(surfacesDir);
      }
    },
  };
}
